### ISSUE TITLE
[idea] Make nodes with more connections larger

### ISSUE THREAD

**Issue by MaxBayly** [tchayen/markdown-links#23]
To show which nodes are the 'hubs' of the graph, it might be nice to be able to display nodes with lots of edges as larger, or make node size a function of connection count (maybe this falls under "Configurable parameters of graph simulation." in the roadmap?)

**Comment by wgslr** [comment]
Personally, I feel like the edges themselves are visible enough to draw attention to the nodes with many of them. I'm not sure making the nodes larger would improve readability of the graph. If anything, I would reserve such markings to things that are _not_ visible otherwise in the graph (e.g. note length, although I don't see actual need for that).

**Comment by nixsee** [comment]
I have to disagree - in a large graph, the edges will look like a hairball. If the major nodes are larger, it will be easier to find them and start to make sense of the graph. 

Here's an example from Obsidian.

![image](https://user-images.githubusercontent.com/24255237/88678155-61fa4c80-d0ab-11ea-9069-47bcbaaa7ded.png)

**Comment by tchayen** [comment]
@nixsee I was just about to let you know that similar thing is being worked on but I noticed that you are already well aware of that 😅 .

So in case somebody else is looking: #51.

**Comment by nixsee** [comment]
Could probably close this issue given #51?

**Comment by tchayen** [comment]
Until #51 is merged, it remains an open issue though 😄 .

**Comment by MaxBayly** [comment]
Seems like this has been implemented with #51 , nice!
