### ISSUE TITLE
[idea] Add support for [[file-name|Some Text]] syntax.

### ISSUE THREAD

**Issue by celadonfish** [tchayen/markdown-links#29]
This is syntax used by [this extension](https://marketplace.visualstudio.com/items?itemName=svsool.markdown-memo) which seems to be a more developed/advanced interlinked markdown extension than many others. I'm not sure if this syntax is being used anywhere else but it seems like a good way of linking notes this way while still being able to provide a title.

**Comment by celadonfish** [comment]
[This](https://github.com/svsool/vscode-memo/blob/master/help/Attachments/Links%20labeling.png) is what these links look like in action (taken from [here](https://github.com/svsool/vscode-memo)).

**Comment by tchayen** [comment]
This kind of syntax is usually called [Wiki links](https://en.wikipedia.org/wiki/Help:Link#Wikilinks_(internal_links)) (since first/most popular use case is various kinds of wikis) and the alias part after `|` also comes from that convention.

Thanks for reporting this! I have added it to the list of desired supported optional syntaxes that I am gathering in #28.

I am closing this issue and let's move discussion there in case you feel like adding something. I find it important to discuss that in context of other planned syntaxes so we are aware of what might be conflicting and what is common.
